name: Build product

env:
  IMAGE: dabot

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build product
      run: make
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE:ci_$(date +%s)
